spring:
  application:
    name: ai-social-content-generator

  datasource:
    url: jdbc:mysql://localhost:3306/social-content?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use update for dev; change to validate in production
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 2000000

# (Optional) Redis if you're using caching:
# redis:
#   host: localhost
#   port: 6379

app:
  jwtSecret: change_this_secret
  jwtExpirationMs: 86400000
  frontend:
    success-url: http://localhost:5173/?success=true
    cancel-url: http://localhost:5173/pricing


llm:
  apiUrl: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
  apiKey: ${LLM_API_KEY}

stripe:
  secret:
    key: ${STRIPE_SECRET}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}
  price:
    pro: ${STRIPE_PRO_PRICE_PRODUCT}


