spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use update for dev; change to validate in production
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 2000000


app:
  frontend:
    success-url: https://ai-social-content-gen-production.up.railway.app/?success=true
    cancel-url: https://ai-social-content-gen-production.up.railway.app/pricing



